# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Deploy
  displayName: Deploy to IIS
  
  jobs:
  
  - deployment: DeploytoIIS
  
    displayName: Deploy the web application to dev environment
    environment: php

    pool:
      name: Default

    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'portalcms-ci'
              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'

          # - task: PowerShell@2
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       Set-Location -Path C:\inetpub\portal-ci
          #       git clone https://github.com/victorwitkamp/PortalCMS/
          #     failOnStderr: true
