CREATE TABLE IF NOT EXISTS mail_recipients (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  recipient VARCHAR(255) DEFAULT NULL,
  mail_id INT DEFAULT NULL,
  CreationDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModificationDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)