<?php
return [
    'URL' => 'https://portal.beukonline.nl/',
    'DEFAULT_CONTROLLER' => 'Login',
    'DEFAULT_ACTION' => 'Index',
    'PATH_LOGO' =>  DIR_ROOT . 'content/logo/',
    'PATH_LOGO_PUBLIC' => 'content/logo/',
    'PATH_ATTACHMENTS' =>  'content/attachments/',
    'PATH_ATTACHMENTS_PUBLIC' => 'content/attachments/',
    'DB_TYPE' => 'mysql',
    'DB_HOST' => 'silent-field.49425portal.dbinf.buildingtogether.io',
    'DB_NAME' => '49425portal',
    'DB_USER' => '49425portal',
    'DB_PASS' => 'Zh@_@x@T_reQ9#pQ',
    'DB_PORT' => '3306',
    'DB_CHARSET' => 'utf8mb4',
    'DB_COLLATE' => 'utf8mb4_general_ci',
    'COOKIE_RUNTIME' => 1209600,
    'COOKIE_PATH' => '/',
    'COOKIE_DOMAIN' => '',
    'COOKIE_SECURE' => true,
    'COOKIE_HTTP' => true,
    'FB_APP_ID' => '1991997357725439',
    'FB_APP_SECRET' => 'a033dce887f749e53907fb710ae253bc',
    'FB_LOGIN_URL' => 'https://portal.beukonline.nl/login/ext/fb/fb-callback-login.php',
    'FB_ASSIGN_URL' => 'https://portal.beukonline.nl/login/ext/fb/fb-callback.php',
    'ENCRYPTION_KEY' => '6#x0gÊìf^25cL1f$08&',
    'HMAC_SALT' => '8qk9c^4L6d#15tM8z7n0%',
    'EMAIL_PASSWORD_RESET_URL' => 'login/resetPassword.php',
    'EMAIL_PASSWORD_RESET_SUBJECT' => 'Password reset',
    'EMAIL_VERIFICATION_URL' => 'register/verify',
    'EMAIL_VERIFICATION_FROM_EMAIL' => 'vrijwilligers@beukonline.nl',
    'EMAIL_VERIFICATION_FROM_NAME' => 'My Project',
    'EMAIL_VERIFICATION_SUBJECT' => 'Account activation',
    'EMAIL_VERIFICATION_CONTENT' => 'Please click on this link to activate your account: '
];
