<?PHP

/**
 * TEXTS USED IN THE APPLICATION.
 * THESE TEXTS ARE USED VIA TEXT::GET('FEEDBACK_USERNAME_ALREADY_TAKEN').
 * COULD BE EXTENDED TO I18N ETC.
 */
RETURN ARRAY(
    // GENERAL
    "DAY" => "DAG",
    "YEAR" => "JAAR",
    "MONTH" => "MAAND",
    // DAYS
    "DAY_01"=>"Maandag",
    "DAY_02"=>"Dinsdag",
    "DAY_03"=>"Woensdag",
    "DAY_04"=>"Donderdag",
    "DAY_05"=>"Vrijdag",
    "DAY_06"=>"Zaterdag",
    "DAY_07"=>"Zondag",
    // MONTHS
    "MONTH_01" => "Januari",
    "MONTH_02" => "Februari",
    "MONTH_03" => "Maart",
    "MONTH_04" => "April",
    "MONTH_05" => "Mei",
    "MONTH_06" => "Juni",
    "MONTH_07" => "July",
    "MONTH_08" => "Augustus",
    "MONTH_09" => "September",
    "MONTH_10" => "Oktober",
    "MONTH_11" => "November",
    "MONTH_12" => "December",
    // GENERAL
    "LABEL_ADD" => "TOEVOEGEN",
    "LABEL_EDIT" => "BEWERKEN",
    "LABEL_DELETE" => "VERWIJDEREN",
    "LABEL_IMPORT" => "IMPORTEREN",
    "LABEL_CLOSE" => "SLUITEN",
    "LABEL_NOT_FOUND" => "NIET GEVONDEN",
    // <?PHP ECHO TEXT::GET('LABEL_ADD');

    "LABEL_LOG_IN" => "LOG-IN",
    "LABEL_CONTINUE_WITH_FACEBOOK" => "LOG-IN",
    "LABEL_REMEMBER_ME" => "ONTHOUDEN",
    "LABEL_FORGOT_PASSWORD" => "WACHTWOORD VERGETEN",

    // NAV
    "LABEL_SIGN_OUT" => "UITLOGGEN",
    "LABEL_SIGNED_IN_AS" => "INGELOGD ALS",

    // NAVIGATION
    "NAV_TITLE_HOME" => "HOME",
    "NAV_TITLE_MENU" => "MENU",
    "NAV_TITLE_EMAIL" => "E-MAIL",
    "TITLE_EVENTS" => "EVENTS",
    "TITLE_MEMBERS" => "LEDEN",
    "NAV_TITLE_RENTAL" => "VERHUUR",
    "TITLE_CONTRACTS" => "CONTRACTEN",
    "TITLE_INVOICES" => "FACTUREN",
    "TITLE_PRODUCTS" => "PRODUCTEN",
    "NAV_TITLE_SETTINGS" => "INSTELLINGEN",
    "TITLE_SITE_SETTINGS" => "SITE INSTELLINGEN",
    "TITLE_USER_MANAGEMENT" => "GEBRUIKERS BEHEREN",
    "TITLE_ROLE_MANAGEMENT" => "ROLLEN BEHEREN",
    "TITLE_RECENT_ACTIVITY" => "RECENTE ACTIVITEIT",
    "TITLE_DEBUG" => "DEBUG MODE",


    // HOME
    "TITLE_HOME" => "HOME",
    "LABEL_EDIT_PAGE" => "PAGINA_BEWERKEN",
    "LABEL_LAST_MODIFIED" => "LAATST_BEWERKT",

    // WIDGET: COMING EVENTS
    "TITLE_WIDGET_COMING_EVENTS" => "KOMENDE EVENEMENTEN",
    // WIDGET: DEBUG
    "TITLE_WIDGET_DEBUG" => "DEBUG",

    // EVENTS
    "TITLE_EVENTS" => "EVENEMENTEN",
    "LABEL_EVENT_DETAILS" => "EVENEMENT DETAILS",
    "LABEL_EVENT_TITLE" => "TITEL",
    "LABEL_EVENT_ADDED_BY" => "TOEGEVOEGD DOOR",
    "LABEL_EVENT_START" => "START",
    "LABEL_EVENT_END" => "EINDE",
    "LABEL_EVENT_DESC" => "BESCHRIJVING",

    // RENTAL
    // OVERVIEW
    "TITLE_OVERVIEW" => "OVERZICHT",
    // CONTRACTS
    "LABEL_CONTRACT_INVOICES_FOR_ID" => "Facturen voor contract Id: ",

    // SITE SETTINGS
    "LABEL_SETTINGS_GENERAL" => "ALGEMEEN",
    "LABEL_SITE_NAME" => "NAAM",
    "LABEL_SITE_DESC" => "SLOGAN TEXT",
    "LABEL_SITE_DESC_TYPE" => "SLOGAN TYPE",
    "LABEL_SITE_THEME" => "THEMA",
    "LABEL_SITE_LAYOUT" => "LAYOUT",
    "LABEL_SITE_URL" => "URL",
    "LABEL_SITE_LOGO" => "LOGO",
    "LABEL_SITE_WIDGETS" => "WIDGETS",
    // ROLE MANAGEMENT
    "TITLE_ROLE" => "Details van",
    "LABEL_ROLE_GENERAL" => "Algemeen",
    "LABEL_ROLE_PERMISSIONS" => "Permissies",
    "LABEL_ROLE_ADD_PERMISSION" => "Permissie toevoegen",

    // MAILSCHEDULER
    "TITLE_MAIL_SCHEDULER" => "E-MAIL BEHEER",
    "LABEL_NEW_EMAIL" => "NEW_EMAIL",
    "LABEL_SEND_EMAIL" => "SEND_EMAIL",
    "LABEL_DELETE_EMAIL" => "DELETE_EMAIL",

    "TITLE_MAIL_HISTORY" => "E-MAIL GESCHIEDENIS",
    // MAIL TEMPLATES
    "TITLE_MAIL_TEMPLATES" => "E-MAIL TEMPLATES",

    // MAILDETAILS
    "TITLE_MAIL_DETAILS" => "Details voor Mail ID: ",
    "LABEL_MAILDETAILS_ID" => "MAILDETAILS_ID",
    "LABEL_MAILDETAILS_SENDER" => "MAILDETAILS_SENDER",
    "LABEL_MAILDETAILS_RECIPIENT" => "MAILDETAILS_RECIPIENT",
    "LABEL_MAILDETAILS_SUBJECT" => "MAILDETAILS_SUBJECT",
    "LABEL_MAILDETAILS_BODY" => "MAILDETAILS_BODY",
    "LABEL_MAILDETAILS_MEMBER_ID" => "MAILDETAILS_MEMBER_ID",
    "LABEL_MAILDETAILS_USER_ID" => "MAILDETAILS_USER_ID",
    "LABEL_MAILDETAILS_STATUS" => "MAILDETAILS_STATUS",
    "LABEL_MAILDETAILS_ERROR" => "MAILDETAILS_ERROR",
    "LABEL_MAILDETAILS_DATE_SENT" => "MAILDETAILS_DATE_SENT",
    "LABEL_MAILDETAILS_DATE_CREATION" => "MAILDETAILS_DATE_CREATION",
    "LABEL_MAILDETAILS_DATE_MODIFICATION" => "MAILDETAILS_DATE_MODIFICATION",

    // MY ACCOUNT
    "TITLE_MY_ACCOUNT" => "MIJN ACCOUNT",
    "LABEL_ACCOUNT_DETAILS" => "ACCOUNTGEGEVENS",
    "LABEL_CHANGE_PASSWORD" => "WACHTWOORD WIJZIGEN",
    "LABEL_CURRENT_PASSWORD" => "HUIDIG WACHTWOORD",
    "LABEL_NEW_PASSWORD" => "NIEUW WACHTWOORD",
    "LABEL_CONFIRM_PASSWORD" => "BEVESTIG WACHTWOORD",
    "LABEL_CHANGE_USERNAME" => "GEBRUIKERSNAAM WIJZIGEN",
    "LABEL_NEW_USERNAME" => "NIEUWE GEBRUIKERSNAAM",

    // USER
    "LABEL_USER_ID" => "USER ID",
    "LABEL_USER_NAME" => "GEBRUIKERSNAAM",
    "LABEL_USER_EMAIL" => "E-MAILADRES",
    "LABEL_USER_ACCOUNT_TYPE" => "TYPE",
    "LABEL_USER_PROVIDER_TYPE" => "PROVIDER TYPE",
    "LABEL_USER_LAST_LOGIN_TIMESTAMP" => "LAATSTE AANMELDING",
    "LABEL_USER_FBID" => "FACEBOOK ID",
    "LABEL_USER_CLEAR_FBID" => "VERWIJDER KOPPELING",
    "LABEL_SUBMIT" => "OPSLAAN",

    // FEEDBACK
    "FEEDBACK_UNKNOWN_ERROR" => "UNKNOWN ERROR OCCURRED!",
    "FEEDBACK_DELETED" => "YOUR ACCOUNT HAS BEEN DELETED.",
    "FEEDBACK_ACCOUNT_SUSPENDED" => "ACCOUNT SUSPENDED FOR ",
    "FEEDBACK_ACCOUNT_SUSPENSION_DELETION_STATUS" => "THIS USER'S SUSPENSION / DELETION STATUS HAS BEEN EDITED.",
    "FEEDBACK_ACCOUNT_CANT_DELETE_SUSPEND_OWN" => "YOU CAN NOT DELETE OR SUSPEND YOUR OWN ACCOUNT.",
    "FEEDBACK_ACCOUNT_USER_SUCCESSFULLY_KICKED" => "THE SELECTED USER HAS BEEN SUCCESSFULLY KICKED OUT OF THE SYSTEM (BY RESETTING THIS USER'S SESSION)",
    "FEEDBACK_PASSWORD_WRONG_3_TIMES" => "YOU HAVE TYPED IN A WRONG PASSWORD 3 OR MORE TIMES ALREADY. PLEASE WAIT 30 SECONDS TO TRY AGAIN.",
    "FEEDBACK_ACCOUNT_NOT_ACTIVATED_YET" => "YOUR ACCOUNT IS NOT ACTIVATED YET. PLEASE CLICK ON THE CONFIRM LINK IN THE MAIL.",
    // "FEEDBACK_USERNAME_OR_PASSWORD_WRONG" => "THE USERNAME OR PASSWORD IS INCORRECT. PLEASE TRY AGAIN.",
    "FEEDBACK_USERNAME_OR_PASSWORD_WRONG" => "FEEDBACK_USERNAME_OR_PASSWORD_WRONG",
    "FEEDBACK_USER_DOES_NOT_EXIST" => "THIS USER DOES NOT EXIST.",
    "FEEDBACK_LOGIN_FAILED" => "LOGIN FAILED.",
    "FEEDBACK_LOGIN_FAILED_3_TIMES" => "LOGIN FAILED 3 OR MORE TIMES ALREADY. PLEASE WAIT 30 SECONDS TO TRY AGAIN.",
    "FEEDBACK_USERNAME_FIELD_EMPTY" => "USERNAME FIELD WAS EMPTY.",
    "FEEDBACK_PASSWORD_FIELD_EMPTY" => "PASSWORD FIELD WAS EMPTY.",
    "FEEDBACK_USERNAME_OR_PASSWORD_FIELD_EMPTY" => "USERNAME OR PASSWORD FIELD WAS EMPTY.",
    "FEEDBACK_USERNAME_EMAIL_FIELD_EMPTY" => "USERNAME / EMAIL FIELD WAS EMPTY.",
    "FEEDBACK_EMAIL_FIELD_EMPTY" => "EMAIL FIELD WAS EMPTY.",
    "FEEDBACK_EMAIL_REPEAT_WRONG" => "EMAIL AND EMAIL REPEAT ARE NOT THE SAME",
    "FEEDBACK_EMAIL_AND_PASSWORD_FIELDS_EMPTY" => "EMAIL AND PASSWORD FIELDS WERE EMPTY.",
    "FEEDBACK_USERNAME_SAME_AS_OLD_ONE" => "SORRY, THAT USERNAME IS THE SAME AS YOUR CURRENT ONE. PLEASE CHOOSE ANOTHER ONE.",
    "FEEDBACK_USERNAME_ALREADY_TAKEN" => "SORRY, THAT USERNAME IS ALREADY TAKEN. PLEASE CHOOSE ANOTHER ONE.",
    "FEEDBACK_USER_EMAIL_ALREADY_TAKEN" => "SORRY, THAT EMAIL IS ALREADY IN USE. PLEASE CHOOSE ANOTHER ONE.",
    "FEEDBACK_USERNAME_CHANGE_SUCCESSFUL" => "YOUR USERNAME HAS BEEN CHANGED SUCCESSFULLY.",
    "FEEDBACK_USERNAME_AND_PASSWORD_FIELD_EMPTY" => "USERNAME AND PASSWORD FIELDS WERE EMPTY.",
    "FEEDBACK_USERNAME_DOES_NOT_FIT_PATTERN" => "USERNAME DOES NOT FIT THE NAME PATTERN: ONLY A-Z AND NUMBERS ARE ALLOWED, 2 TO 64 CHARACTERS.",
    "FEEDBACK_EMAIL_DOES_NOT_FIT_PATTERN" => "SORRY, YOUR CHOSEN EMAIL DOES NOT FIT INTO THE EMAIL NAMING PATTERN.",
    "FEEDBACK_EMAIL_SAME_AS_OLD_ONE" => "SORRY, THAT EMAIL ADDRESS IS THE SAME AS YOUR CURRENT ONE. PLEASE CHOOSE ANOTHER ONE.",
    "FEEDBACK_EMAIL_CHANGE_SUCCESSFUL" => "YOUR EMAIL ADDRESS HAS BEEN CHANGED SUCCESSFULLY.",
    "FEEDBACK_CAPTCHA_WRONG" => "THE ENTERED CAPTCHA SECURITY CHARACTERS WERE WRONG.",
    "FEEDBACK_PASSWORD_REPEAT_WRONG" => "PASSWORD AND PASSWORD REPEAT ARE NOT THE SAME.",
    "FEEDBACK_PASSWORD_TOO_SHORT" => "PASSWORD HAS A MINIMUM LENGTH OF 6 CHARACTERS.",
    "FEEDBACK_USERNAME_TOO_SHORT_OR_TOO_LONG" => "USERNAME CANNOT BE SHORTER THAN 2 OR LONGER THAN 64 CHARACTERS.",
    "FEEDBACK_ACCOUNT_SUCCESSFULLY_CREATED" => "YOUR ACCOUNT HAS BEEN CREATED SUCCESSFULLY AND WE HAVE SENT YOU AN EMAIL. PLEASE CLICK THE VERIFICATION LINK WITHIN THAT MAIL.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_FAILED" => "SORRY, WE COULD NOT SEND YOU AN VERIFICATION MAIL. YOUR ACCOUNT HAS NOT BEEN CREATED.",
    "FEEDBACK_ACCOUNT_CREATION_FAILED" => "SORRY, YOUR REGISTRATION FAILED. PLEASE GO BACK AND TRY AGAIN.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_ERROR" => "VERIFICATION MAIL COULD NOT BE SENT DUE TO: ",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_SUCCESSFUL" => "A VERIFICATION MAIL HAS BEEN SENT SUCCESSFULLY.",
    "FEEDBACK_ACCOUNT_ACTIVATION_SUCCESSFUL" => "ACTIVATION WAS SUCCESSFUL! YOU CAN NOW LOG IN.",
    "FEEDBACK_ACCOUNT_ACTIVATION_FAILED" => "SORRY, NO SUCH ID/VERIFICATION CODE COMBINATION HERE! IT MIGHT BE POSSIBLE THAT YOUR MAIL PROVIDER (YAHOO? HOTMAIL?) AUTOMATICALLY VISITS LINKS IN EMAILS FOR ANTI-SCAM SCANNING, SO THIS ACTIVATION LINK MIGHT BEEN CLICKED WITHOUT YOUR ACTION. PLEASE TRY TO LOG IN ON THE MAIN PAGE.",
    "FEEDBACK_AVATAR_UPLOAD_SUCCESSFUL" => "AVATAR UPLOAD WAS SUCCESSFUL.",
    "FEEDBACK_AVATAR_UPLOAD_WRONG_TYPE" => "ONLY JPEG AND PNG FILES ARE SUPPORTED.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_SMALL" => "AVATAR SOURCE FILE'S WIDTH/HEIGHT IS TOO SMALL. NEEDS TO BE 100X100 PIXEL MINIMUM.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_BIG" => "AVATAR SOURCE FILE IS TOO BIG. 5 MEGABYTE IS THE MAXIMUM.",
    "FEEDBACK_AVATAR_FOLDER_DOES_NOT_EXIST_OR_NOT_WRITABLE" => "AVATAR FOLDER DOES NOT EXIST OR IS NOT WRITABLE. PLEASE CHANGE THIS VIA CHMOD 775 OR 777.",
    "FEEDBACK_AVATAR_IMAGE_UPLOAD_FAILED" => "SOMETHING WENT WRONG WITH THE IMAGE UPLOAD.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_SUCCESSFUL" => "YOU SUCCESSFULLY DELETED YOUR AVATAR.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_NO_FILE" => "YOU DON'T HAVE A CUSTOM AVATAR.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_FAILED" => "SOMETHING WENT WRONG WHILE DELETING YOUR AVATAR.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_FAIL" => "COULD NOT WRITE TOKEN TO DATABASE.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_MISSING" => "NO PASSWORD RESET TOKEN.",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_ERROR" => "PASSWORD RESET MAIL COULD NOT BE SENT DUE TO: ",
    // "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL" => "A PASSWORD RESET MAIL HAS BEEN SENT SUCCESSFULLY.",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL" => "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL",
    "FEEDBACK_PASSWORD_RESET_LINK_EXPIRED" => "YOUR RESET LINK HAS EXPIRED. PLEASE USE THE RESET LINK WITHIN ONE HOUR.",
    "FEEDBACK_PASSWORD_RESET_COMBINATION_DOES_NOT_EXIST" => "USERNAME/VERIFICATION CODE COMBINATION DOES NOT EXIST.",
    "FEEDBACK_PASSWORD_RESET_LINK_VALID" => "PASSWORD RESET VALIDATION LINK IS VALID. PLEASE CHANGE THE PASSWORD NOW.",
    "FEEDBACK_PASSWORD_CHANGE_SUCCESSFUL" => "PASSWORD SUCCESSFULLY CHANGED.",
    "FEEDBACK_PASSWORD_CHANGE_FAILED" => "SORRY, YOUR PASSWORD CHANGING FAILED.",
    "FEEDBACK_PASSWORD_NEW_SAME_AS_CURRENT" => "NEW PASSWORD IS THE SAME AS THE CURRENT PASSWORD.",
    "FEEDBACK_PASSWORD_CURRENT_INCORRECT" => "CURRENT PASSWORD ENTERED WAS INCORRECT.",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_SUCCESSFUL" => "ACCOUNT TYPE CHANGE SUCCESSFUL",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_FAILED" => "ACCOUNT TYPE CHANGE FAILED",
    "FEEDBACK_NOTE_CREATION_FAILED" => "NOTE CREATION FAILED.",
    "FEEDBACK_NOTE_EDITING_FAILED" => "NOTE EDITING FAILED.",
    "FEEDBACK_NOTE_DELETION_FAILED" => "NOTE DELETION FAILED.",
    "FEEDBACK_COOKIE_INVALID" => "YOUR REMEMBER-ME-COOKIE IS INVALID.",
    "FEEDBACK_COOKIE_LOGIN_SUCCESSFUL" => "YOU WERE SUCCESSFULLY LOGGED IN VIA THE REMEMBER-ME-COOKIE.",
    // "FEEDBACK_LOGOUT_SUCCESSFUL" => "YOU WERE SUCCESSFULLY LOGGED OUT."
        "FEEDBACK_LOGIN_SUCCESSFUL" => "LOGIN_SUCCESSFUL",

    "FEEDBACK_LOGOUT_SUCCESSFUL" => "LOGOUT_SUCCESSFUL",
    "FEEDBACK_SESSION_EXPIRED" => "SESSION_EXPIRED",

    "FEEDBACK_SUCCESSFUL_FACEBOOK_LOGIN" => "SUCCESSFUL_FACEBOOK_LOGIN",
    "FEEDBACK_FACEBOOK_LOGIN_FAILED" => "FACEBOOK_LOGIN_FAILED",
);
