INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServer','localhost');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerPort','25');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerSecure','0');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerAuth','1');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerUsername','');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerPassword','');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailServerDebug','0');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailFromName','');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailFromEmail','');
INSERT INTO `site_settings` (`setting`, `string_value`) VALUES ('MailIsHTML', '1');